# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c3ec044023d690c5d4149d0432d82beededafa8e3c12f40ee0c6c6a4da6d45f2e2ff37c762903e694cf6c037dc2f4b200d3fd9d40df00eb496167a0b0943ff3

test:
  secret_key_base: 4ee34813453e1ccbcf6251ee0607e7d34725bd08897e2d7e3d4e98791625cc731b2cb7daab4b7161a9948311fa6404f139981adebe644e6f7fbe3a0c2cdaa94b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
